### ISSUE TITLE
Should `Framebuffer` be `Sync`?

### ISSUE THREAD

**Issue by UditDey** [jasondyoungberg/limine-rs#29]
What I wanted to do in my kernel was that after boot it would read the `FramebufferResponse` and store the first `Framebuffer` it contained into a global static, which would in turn be used by my print function.

But I couldn't do that since `Framebuffer` is not `Sync` and so can't be put in a global static, and you can't use unsafe to get past this either. In fact `FramebufferResponse` has `unsafe impl Sync` on it, but the `Framebuffer` struct it returns does not.

I think marking it as `Sync` should be fine, unless I'm missing something

**Comment by adavis628** [comment]
Since none of `FrameBuffer`'s methods dereference its pointer, it should be safe to mark it as both `Send` and `Sync`. Right now, I just use a wrapper struct to do this:
```rust
pub struct Screen<'a> {
    pub fb: Framebuffer<'a>,
}
unsafe impl Send for Screen<'_> {}
unsafe impl Sync for Screen<'_> {}
```
